INSERT INTO cities VALUES
(1, 'Adana'),
(2, 'Adıyaman'),
(3, 'Afyonkarahisar'),
(4, 'Ağrı'),
(5, 'Amasya'),
(6, 'Ankara'),
(7, 'Antalya'),
(8, 'Artvin'),
(9, 'Aydın'),
(10, 'Balıkesir'),
(11, 'Bilecik'),
(12, 'Bingöl'),
(13, 'Bitlis'),
(14, 'Bolu'),
(15, 'Burdur'),
(16, 'Bursa'),
(17, 'Çanakkale'),
(18, 'Çankırı'),
(19, 'Çorum'),
(20, 'Denizli'),
(21, 'Diyarbakır'),
(22, 'Edirne'),
(23, 'Elâzığ'),
(24, 'Erzincan'),
(25, 'Erzurum'),
(26, 'Eskişehir'),
(27, 'Gaziantep'),
(28, 'Giresun'),
(29, 'Gümüşhane'),
(30, 'Hakkâri'),
(31, 'Hatay'),
(32, 'Isparta'),
(33, 'Mersin'),
(34, 'İstanbul'),
(35, 'İzmir'),
(36, 'Kars'),
(37, 'Kastamonu'),
(38, 'Kayseri'),
(39, 'Kırklareli'),
(40, 'Kırşehir'),
(41, 'Kocaeli'),
(42, 'Konya'),
(43, 'Kütahya'),
(44, 'Malatya'),
(45, 'Manisa'),
(46, 'Kahramanmaraş'),
(47, 'Mardin'),
(48, 'Muğla'),
(49, 'Muş'),
(50, 'Nevşehir'),
(51, 'Niğde'),
(52, 'Ordu'),
(53, 'Rize'),
(54, 'Sakarya'),
(55, 'Samsun'),
(56, 'Siirt'),
(57, 'Sinop'),
(58, 'Sivas'),
(59, 'Tekirdağ'),
(60, 'Tokat'),
(61, 'Trabzon'),
(62, 'Tunceli'),
(63, 'Şanlıurfa'),
(64, 'Uşak'),
(65, 'Van'),
(66, 'Yozgat'),
(67, 'Zonguldak'),
(68, 'Aksaray'),
(69, 'Bayburt'),
(70, 'Karaman'),
(71, 'Kırıkkale'),
(72, 'Batman'),
(73, 'Şırnak'),
(74, 'Bartın'),
(75, 'Ardahan'),
(76, 'Iğdır'),
(77, 'Yalova'),
(78, 'Karabük'),
(79, 'Kilis'),
(80, 'Osmaniye'),
(81, 'Düzce') on conflict do nothing;

INSERT INTO ways_of_working VALUES
(1,'Tam Zamanlı'),
(2,'Part Time (Yarı Zamanlı)'),
(3,'Staj'),
(4,'Dönemsel') on conflict do nothing;

INSERT INTO working_times VALUES
(1,'Şirket Çalışanı'),
(2,'Uzaktan Çalışma'),
(3,'Freelance (Serbest Çalışma)') on conflict do nothing;

INSERT INTO job_positions VALUES
(1,'Akbant Operatörü'),
(2,'Adwords Uzmanı'),
(3,'Akademisyen'),
(4,'Akaryakıt Pompa Görevlisi'),
(5,'Analist'),
(6,'Anaokulu Müdürü'),
(7,'Animatör'),
(8,'Anketör'),
(9,'Antrenör'),
(10,'Ar-Ge Mühendisi'),
(11,'Arayüz Geliştirme Uzmanı'),
(12,'Art Direktör / Sanat Yönetmeni'),
(13,'Asansör Ustası'),
(14,'Aşçı'),
(15,'Aşçı Yardımcısı'),
(16,'Asistan'),
(17,'Avukat'),
(18,'Bahçivan'),
(19,'Bakım Elemanı'),
(20,'Bakım Mühendisi'),
(21,'Bale Öğretmneni'),
(22,'Barista'),
(23,'Barmen / Barmaid'),
(24,'Başhekim'),
(25,'Başhemşire'),
(26,'Baskı Operatörü'),
(27,'BeachBoy'),
(28,'Bekçi'),
(29,'BellBoy'),
(30,'Beslenme Uzmanı'),
(31,'Bilgi İşlem Müdürü'),
(32,'Bilgisayar Mühendisi'),
(33,'Bilgisayar Programcısı'),
(34,'Biyokimyager'),
(35,'Biyolog'),
(36,'Bölge Müdürü'),
(37,'Bölge Sorumlusu'),
(38,'Boya Elemanı'),
(39,'Branş Öğretmeni'),
(40,'Broker'),
(41,'Bulaşıkçı'),
(42,'Çağrı Merkezi Elemanı'),
(43,'Camcı'),
(44,'Cankurtaran'),
(45,'Çaycı'),
(46,'Çevirmen'),
(47,'Çevre Mühendisi'),
(48,'Çiçek Ustası'),
(49,'Çırak'),
(50,'Cnc Operatörü'),
(51,'Daire Başkanı'),
(52,'Dalgıç'),
(53,'Danışman'),
(54,'Dans Öğretmeni'),
(55,'Dansçı'),
(56,'Dealer'),
(57,'Denetçi'),
(58,'Depo Elemanı'),
(59,'Desinatör'),
(60,'Dijital Pazarlama Uzmanı'),
(61,'Direksiyon Öğretmeni'),
(62,'Direktör'),
(63,'Diş Hekimi'),
(64,'Diş Teknik Sekreteri'),
(65,'Dış Ticaret Personeli'),
(66,'Diyetisyen'),
(67,'Doğalgaz Ustası'),
(68,'Doktor'),
(69,'Döner Ustası'),
(70,'Ebe'),
(71,'Eczacı'),
(72,'Editör'),
(73,'Eğitmen'),
(74,'Ekip Üyesi'),
(75,'Ekmek Ustası'),
(75,'Eksper'),
(77,'Eksper Asistanı'),
(78,'Elektrik Mühendisi'),
(79,'Elektrik Teknikeri'),
(80,'Elektrik Teknisyeni'),
(81,'Elektrikçi'),
(82,'Elektronik Mühendisi'),
(83,'Elektronik Teknikeri'),
(84,'Elektronik Teknisyeni'),
(85,'Yazılım Mühendisi'),
(86,'Yazılımcı'),
(87,'Yazılım Uzmanı'),
(88,'Yazılım Geliştirici') on conflict do nothing;